name: Frontend Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Generate
        working-directory: ./frontend
        run: npm run generate
        env:
          API_URL: https://api.osrsquery.com
          IMAGE_SERVING_URL: https://cdn.osrsquery.com
          VER: ${{ github.ref }}
          SITE_NAME: "OSRSQuery Admin"
          SITE_DESCRIPTION: "OSRSQuery Admin is the administration site for OSRSQuery.com"
          SITE_IMAGE_URL: https://cdn.boilerplate.giraffeql.com/permanent/android-chrome-512x512.png
          SITE_CONTACT_EMAIL: hello@osrsquery.com
          SITE_DISCORD_LINK: https://discord.gg/Ygt8gEj72G
          SITE_GITHUB_REPOSITORY_URL: https://github.com/osrsquery/osrsquery-api
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./frontend
